services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./back-static:/app/back-static
      - ./back-media:/app/back-media
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    restart: always
    command: celery -A config worker -l info
    depends_on:
      - web


volumes:
  postgres_data:
